### ISSUE TITLE
Question: OneWire Slave Possibility

### ISSUE THREAD

**Issue by GeorgeIoak** [aZholtikov/zh_onewire#1]
I'm doing research on a project where I want to emulate a DS18B20 temp sensor. This would be used to test another board and how it reacts when the "DS18B20" temperature changes.

The write commands for the bus are already done so it would be "*just*" adding the ability to listen to the bus and respond to a few commands like a real DS18B20 sensor would.

Before I started working on this I thought I would check if this was of any interest to you and if so perhaps we could collaborate?

**Comment by aZholtikov** [comment]
Sure. I'm always open to new research. Please switch to email communication (github@azholtikov.ru) to avoid clogging up GitHub.
